#!/usr/bin/env bash
# Packed bundle: decodes embedded payload then evals it.
_decode() {
  base64 -d
}
eval "$(_decode <<'__PAYLOAD__'
IyBHZW5lcmF0ZWQgYnkgc2NyaXB0cy9idW5kbGUtYmFzaC5zaCBvbiAyMDI2LTA2LTEwVDAzOjEwOjQ5WgojIEVudHJ5OiBjb21taXR0aGlzLnNoCiMgTm90ZTogVGhpcyBpcyBhIGJ1bmRsZWQgZmlsZS4gRG8gbm90IGVkaXQgZGlyZWN0bHkuCmV4cG9ydCBfX01BSUFTU19CVU5ETEVEPTEKCmZvciBhcmcgaW4gIiRAIjsgZG8KICBjYXNlICRhcmcgaW4KICAgIC1ofC0taGVscCkKICAgICAgbWFpYXNzIC0tY29tbWl0dGhpcy1oZWxwCiAgICAgIGV4aXQgMAogICAgICA7OwogICAgLXZ8LS12ZXJzaW9uKQogICAgICBtYWlhc3MgLS1jb21taXR0aGlzLXZlcnNpb24gICAgICAjIFRyeSB0byByZWFkIHZlcnNpb24gZnJvbSBwYWNrYWdlLmpzb24gaW4gc2NyaXB0IGRpcmVjdG9yeQogICAgICBleGl0IDAKICAgICAgOzsKICBlc2FjCmRvbmUKCm1haWFzcyAtLWNvbW1pdHMtb25seQo=
__PAYLOAD__
)"
