#!/usr/bin/env bash
# Generated by scripts/bundle-bash.sh on 2026-06-24T22:30:40Z
# Entry: committhis.sh
# Note: This is a bundled file. Do not edit directly.
export __MAIASS_BUNDLED=1

for arg in "$@"; do
  case $arg in
    -h|--help)
      maiass --committhis-help
      exit 0
      ;;
    -v|--version)
      maiass --committhis-version      # Try to read version from package.json in script directory
      exit 0
      ;;
  esac
done

maiass --commits-only
