name: Build and Release

# Trigger only on pushes to main branch
# Uses latest git tag as version basis and creates release with 'v' prefix

permissions:
  contents: write  # Required to create releases
  actions: read

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Keep manual trigger as backup
    inputs:
      version:
        description: 'Version to release (e.g., 0.7.2)'
        required: true
        default: '0.7.2'

jobs:
  build:
    name: Build Cross-Platform Binaries
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build all platforms
      run: npm run build:all
      
    - name: Create release assets
      run: |
        mkdir -p release-assets
        cd release-assets
        
        # Copy and rename binaries with proper naming
        cp ../build/maiass-macos-x64 maiass-macos-intel
        cp ../build/maiass-macos-arm64 maiass-macos-arm64
        cp ../build/maiass-linux-x64 maiass-linux-x64
        cp ../build/maiass-linux-arm64 maiass-linux-arm64
        cp ../build/maiass-win-x64.exe maiass-windows-x64.exe
        cp ../build/maiass-win-arm64.exe maiass-windows-arm64.exe
        
        # Make binaries executable
        chmod +x maiass-*
        
        # Create checksums
        shasum -a 256 maiass-* > checksums.txt
        
        # List created files
        ls -la
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-binaries
        path: release-assets/
        retention-days: 30

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history and tags
        
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: release-binaries
        path: release-assets/
        
    - name: Get version from latest git tag
      id: version
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          echo "tag_name=v${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          # Main branch push - get latest git tag as version
          echo "Available tags:"
          git tag --list --sort=-version:refname | head -10
          
          LATEST_TAG=$(git tag --list --sort=-version:refname | head -1)
          if [ -z "$LATEST_TAG" ]; then
            LATEST_TAG="0.0.0"
            echo "No tags found, using default: $LATEST_TAG"
          else
            echo "Found latest tag: $LATEST_TAG"
          fi
          
          echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "tag_name=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "Using latest git tag as version: $LATEST_TAG"
        fi
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.tag_name }}
        name: "maiass ${{ steps.version.outputs.version }} - Cross-Platform Release"
        body: |
          🎉 **Cross-platform release of maiass!**
          
          AI-powered Git workflow automation tool now available for macOS, Linux, and Windows with self-contained binaries (no Node.js installation required).
          
          ## 🚀 Quick Install
          
          ### Universal Installer (Recommended)
          ```bash
          curl -fsSL https://raw.githubusercontent.com/vsmash/nodemaiass/main/scripts/install.sh | bash
          ```
          
          ### Homebrew (macOS/Linux)
          ```bash
          brew tap vsmash/maiass
          brew install maiass
          ```
          
          ## 📦 Manual Download
          
          Choose your platform:
          
          ### macOS
          - **Apple Silicon (M1/M2/M3):** [maiass-macos-arm64](https://github.com/vsmash/nodemaiass/releases/download/${{ steps.version.outputs.tag_name }}/maiass-macos-arm64)
          - **Intel:** [maiass-macos-intel](https://github.com/vsmash/nodemaiass/releases/download/${{ steps.version.outputs.tag_name }}/maiass-macos-intel)
          
          ### Linux
          - **x64:** [maiass-linux-x64](https://github.com/vsmash/nodemaiass/releases/download/${{ steps.version.outputs.tag_name }}/maiass-linux-x64)
          
          ### Windows
          - **x64:** [maiass-windows-x64.exe](https://github.com/vsmash/nodemaiass/releases/download/${{ steps.version.outputs.tag_name }}/maiass-windows-x64.exe)
          
          ## ✨ What's New
          
          - ✅ **Cross-platform binaries** for macOS, Linux, Windows
          - ✅ **Self-contained** - includes Node.js runtime (no installation required)
          - ✅ **Universal installer** with automatic platform detection
          - ✅ **Homebrew support** for easy installation
          - ✅ **ARM64 support** for Apple Silicon Macs
          
          ## 🔐 Verification
          
          All binaries include SHA256 checksums for verification:
          - **Checksums:** [checksums.txt](https://github.com/vsmash/nodemaiass/releases/download/${{ steps.version.outputs.tag_name }}/checksums.txt)
          
          ## 📋 System Requirements
          
          - **macOS:** 10.15+ (Intel or Apple Silicon)
          - **Linux:** Most distributions (x64)
          - **Windows:** 10+ (x64)
          - **Dependencies:** None (Node.js included in binary)
          
          ## 📝 Note
          
          **Use the binary downloads above** - the "Source code" archives below are for development only and don't include the self-contained executables.
        files: |
          release-assets/maiass-macos-intel
          release-assets/maiass-macos-arm64
          release-assets/maiass-linux-x64
          release-assets/maiass-linux-arm64
          release-assets/maiass-windows-x64.exe
          release-assets/maiass-windows-arm64.exe
          release-assets/checksums.txt
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
